slices:
  - sources:
      - model: Zyphra/Zamba2-7B
        layer_range: [0, 81]
      - model: Zyphra/Zamba2-7B-Instruct
        layer_range: [0, 81]
merge_method: slerp
base_model: Zyphra/Zamba2-7B
parameters:
  t:
    - filter: self_attn
      value: [0.3, 0.5, 0.7, 0.7, 0.5, 0.3]
    - filter: feed_forward
      value: [0.4, 0.6, 0.8, 0.8, 0.6, 0.4]
    - filter: mamba
      value: 0.75
    - filter: layernorm
      value: 0.5
    - value: 0.5
dtype: bfloat16
